# Generated by Django 3.2.18 on 2023-03-19 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_validation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Validation',
            new_name='Valiation',
        ),
        migrations.RenameField(
            model_name='valiation',
            old_name='validation_category',
            new_name='valiation_category',
        ),
        migrations.RenameField(
            model_name='valiation',
            old_name='validation_value',
            new_name='valiation_value',
        ),
    ]
