# Generated by Django 3.2.18 on 2023-03-19 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20230319_1455'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Valiation',
            new_name='Variation',
        ),
        migrations.RenameField(
            model_name='variation',
            old_name='valiation_category',
            new_name='variation_category',
        ),
        migrations.RenameField(
            model_name='variation',
            old_name='valiation_value',
            new_name='variation_value',
        ),
    ]
