# Generated by Django 3.2.18 on 2023-04-27 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
